"""initial schema

Revision ID: 2581d5990449
Revises: 
Create Date: 2026-04-21 15:55:58.278578
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# O TypeDecorator customizado precisa estar importado para ``op.create_table``
# referenciá-lo como ``app.db.types.EncryptedString()``.
import app.db.types  # noqa: F401


revision: str = '2581d5990449'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=True)

    op.create_table('instagram_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('ig_business_account_id', sa.String(length=64), nullable=False),
    sa.Column('ig_user_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('access_token', app.db.types.EncryptedString(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instagram_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_ig_accounts_client_active', ['client_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_instagram_accounts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instagram_accounts_ig_business_account_id'), ['ig_business_account_id'], unique=True)

    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('redirect_after', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index('ix_oauth_states_client_expires', ['client_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_states_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_states_state'), ['state'], unique=True)

    op.create_table('auto_reply_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instagram_account_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_word', sa.String(length=100), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_account_id', 'trigger_word', name='uq_auto_reply_rules_account_trigger')
    )
    with op.batch_alter_table('auto_reply_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_reply_rules_instagram_account_id'), ['instagram_account_id'], unique=False)

    op.create_table('comment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instagram_account_id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.String(length=64), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('commenter_igsid', sa.String(length=64), nullable=True),
    sa.Column('commenter_username', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_events_comment_id'), ['comment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_comment_events_instagram_account_id'), ['instagram_account_id'], unique=False)

    op.create_table('auto_replies_sent',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_event_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'SKIPPED_NO_RULE', 'SKIPPED_DUPLICATE', name='auto_reply_status'), nullable=False),
    sa.Column('recipient_igsid', sa.String(length=64), nullable=True),
    # message_id: Text (ver comentário no modelo — pode ultrapassar 180 chars).
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_subcode', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_event_id'], ['comment_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['auto_reply_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_replies_sent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_replies_sent_comment_event_id'), ['comment_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_replies_sent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auto_replies_sent_comment_event_id'))

    op.drop_table('auto_replies_sent')
    with op.batch_alter_table('comment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_events_instagram_account_id'))
        batch_op.drop_index(batch_op.f('ix_comment_events_comment_id'))

    op.drop_table('comment_events')
    with op.batch_alter_table('auto_reply_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auto_reply_rules_instagram_account_id'))

    op.drop_table('auto_reply_rules')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_state'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_client_id'))
        batch_op.drop_index('ix_oauth_states_client_expires')

    op.drop_table('oauth_states')
    with op.batch_alter_table('instagram_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instagram_accounts_ig_business_account_id'))
        batch_op.drop_index(batch_op.f('ix_instagram_accounts_client_id'))
        batch_op.drop_index('ix_ig_accounts_client_active')

    op.drop_table('instagram_accounts')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_email'))

    op.drop_table('clients')
    # ### end Alembic commands ###
